-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 00:31:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`inicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`inicio` (
  `id_inicio` INT NULL,
  `logo` VARCHAR(200) NULL,
  `link_pagina` VARCHAR(200) NULL,
  PRIMARY KEY (`id_inicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`navbar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`navbar` (
  `id_navbar` INT NULL,
  `link_linkedin` VARCHAR(100) NULL,
  `link_github` VARCHAR(100) NULL,
  `link_codepen` VARCHAR(100) NULL,
  PRIMARY KEY (`id_navbar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`sobremi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`sobremi` (
  `id_sobremi` INT NULL,
  `banner` VARCHAR(200) NULL,
  `imagen_perfil` VARCHAR(200) NULL,
  `nombrre` VARCHAR(200) NULL,
  `apellido` VARCHAR(200) NULL,
  `informacion` VARCHAR(200) NULL,
  PRIMARY KEY (`id_sobremi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`educacion` (
  `id_educacion` INT NULL,
  `nombre_institucion` VARCHAR(200) NULL,
  `logo_institucion` VARCHAR(200) NULL,
  `nivel_estudios` VARCHAR(200) NULL,
  `sobremi_id_sobremi` INT NOT NULL,
  PRIMARY KEY (`id_educacion`, `sobremi_id_sobremi`),
  INDEX `fk_educacion_sobremi_idx` (`sobremi_id_sobremi` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_sobremi`
    FOREIGN KEY (`sobremi_id_sobremi`)
    REFERENCES `portfolio`.`sobremi` (`id_sobremi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`proyectos` (
  `id_proyectos` INT NULL,
  `nombre_proyecto` VARCHAR(200) NULL,
  `descripcion` VARCHAR(200) NULL,
  `link_proyecto` VARCHAR(200) NULL,
  `sobremi_id_sobremi` INT NOT NULL,
  PRIMARY KEY (`id_proyectos`, `sobremi_id_sobremi`),
  INDEX `fk_proyectos_sobremi1_idx` (`sobremi_id_sobremi` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_sobremi1`
    FOREIGN KEY (`sobremi_id_sobremi`)
    REFERENCES `portfolio`.`sobremi` (`id_sobremi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
